### PR TITLE
Remove plugin deprecated code for Intellij IDEA 2022.3.2

### PR DESCRIPTION
**Pull request by hewison-chris**
A start on removing some deprecated methods as highlighted as problems when using Intellij IDEA 2022.3.2

### CODE REVIEW

**Comment by blackeyeddan** [comment]
Great to see some energy here. Thank you for the work!

I keep an old version of IntelliJ community edition around JUST so I can work on my Elm projects. I'd love to be able to use a modern version of IntelliJ. I hope to see your efforts pay off to that end.

Thanks again!

**Comment by paulwwisl** [comment]
I think making regular releases is more important than starting larger changes
as most time would be consumed by need to test, while smaller reales are still needed just to be sure to keep in pace with IntelliJ platform

**Comment by boxed** [comment]
@paulwwisl the problem is that this repo is abandoned. Someone needs to do a hard fork and publish this project under a new name in the intellij plugin registry.

**Comment by matejcerny** [comment]
Hey @hewison-chris, I built your latest commit in the `move_files` branch, and it works like a charm in IntelliJ 2023.2.5. I know that there is still a lot to do, but maybe you can publish it. It will definitely help everyone on the latest IntelliJ. Great work! 🎉

**Comment by raphaelpereira** [comment]
> @paulwwisl the problem is that this repo is abandoned. Someone needs to do a hard fork and publish this project under a new name in the intellij plugin registry.

there are 16 contributors and none can publish?

**Comment by boxed** [comment]
@raphaelpereira "contributor" just means the owner of this repo pressed merge on a PR. This has nothing to do with the permissions on the jetbrains plugin marketplace. And yes. This is what it means.

**Comment by raphaelpereira** [comment]
> @raphaelpereira "contributor" just means the owner of this repo pressed merge on a PR. This has nothing to do with the permissions on the jetbrains plugin marketplace. And yes. This is what it means.

Sorry @boxed my bad! I thought they had write permission. So we really need a fork and a new plugin registry.

**Comment by cies** [comment]
CI produces an error:

```
 [gradle-intellij-plugin :verifyPluginConfiguration] The following plugin configuration issues were found:
- The 'since-build' property is lower than the target IntelliJ Platform major version: 211 < 223.
- The Java configuration specifies targetCompatibility=17 but since-build='211' property requires targetCompatibility=11.
- The Kotlin configuration specifies jvmTarget=17 but since-build='211' property requires jvmTarget=11.
```

I think it is because I messed with the since-until version while merging.

**Review by cies — APPROVED** [review]

**Comment by matejcerny** [comment]
You are probably right, maybe just try to change the since value from `211` to `223`

**Comment by cies** [comment]
I'm closing this as all improvements have been applied to the current `master` branch and `upgrade-colormath` branch.

**Pull request closed without merging**
